name: gg_periodic_timer
description: A timer that can be started, stopped and restarted again. Also multiple listners can be added.
version: 1.0.0+beta.1
repository: https://github.com/inlavigo/gg_periodic_timer

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_lints: ^2.0.1
  fake_async: ^1.3.1
