name: gg_periodic_timer
description: A timer that can be started, stopped and restarted again. Also multiple listners can be added.
version: 1.0.6
repository: https://github.com/inlavigo/gg_periodic_timer

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  fake_async: ^1.3.1
  args: ^2.4.2
  gg_capture_print: ^1.0.2